notifications:
  email: false

# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
node_js:
  - "0"
  - 4
  - 5
before_script:
  - npm prune
script:
  - npm run compile
  - npm run cover
  - npm run lint
