notifications:
  email: false

# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - 4
  - 6
  - 8
  - 9
script:
  - npm run lint
  - npm run compile
  - npm run cover
